spring:
    datasource:
        url: jdbc:mysql://localhost:3306/test1?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
        username: root
        password: p@ssword
        driver-class-name: com.mysql.cj.jdbc.Driver

    jpa:
        properties.hibernate.id.new_generator_mappings: false
        generate-ddl: true
        show-sql: true
        properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
        hibernate:
            ddl-auto: create
server:
    port: 8082